# Generated by Django 5.0.4 on 2024-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_picture_default.jpg', null=True, upload_to=''),
        ),
    ]
