# Generated by Django 5.0.4 on 2024-04-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_name_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='limited_integer_field',
            new_name='discount',
        ),
    ]
