# Generated by Django 5.0.4 on 2024-04-27 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_limited_integer_field_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(1)]),
        ),
    ]
