# Generated by Django 5.0.4 on 2024-06-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_purchase_purchaseproduct_purchase_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
    ]
